CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
VIDEO_TOKEN_INDEX = -200
PERSON_TOKEN_INDEX = -199
DEFAULT_VIDEO_TOKEN = "<video>"

